api: 
  url: https://apptwo.contrastsecurity.com/Contrast
  api_key: LvRc6U3fkEkW0KINw50iM9RYJbcgn30j
  service_key: EZ1SYTNS55J76CO2
  user_name: agent_540b5bd1-ecd2-447a-8752-1a7aa3517541@SaadsBeachParadise
agent: 
  service: 
    enable: true
    logger: 
      path: contrast_service.log
      level: ERROR
    host: 127.0.0.1
    port: 30555
application: 
  metadata: test="<value>"